name: Build (ESP-IDF)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.4.1
          target: esp32s3
          path: .

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: room-environment-monitor-${{ github.sha }}
          path: |
            build/*.bin
            build/*.elf
            build/*.map
            build/bootloader/bootloader.bin
            build/partition_table/partition-table.bin
          if-no-files-found: error
